### PR TITLE
Path is now a List of Strings

### LINKED ISSUE #53: Multiple Directories
Is it possible to Compress-7zip multiple directories within a directory?  I can't find anything about it in the documentation.

### PR DESCRIPTION
**Pull request by mattiasmaahl**
Fixes #53 

As I had the need to be able to add both files and Directories in
a script I'm running, I made these changes to this Module. Now
I thought I would share them with the repo.

Please let me know if I need to add anything more to this.

In a gist: I Changed how the Execute function searches and adds files to
the list of files to compress. this also meant I had to reimplement the
the Filter and DisableRecursion Options as well.

- Adding in gitignore to also ignore vs code folders.
- Adding functionality to list multiple files/folders to Path parameter
- Reworking Filter to apply to all directories listed in
  Path CLI-Parameter
- Reworking the Recursive search to apply to the new file-search routine

### CODE REVIEW

**Comment by mattiasmaahl** [comment]
Thought I might add an example on how to use the Path option:
You separate the files and folders by a comma (,) and type them out in one line.
Files that have spaces in them need to be quoted!

```powershell
Compress-7Zip -Path .\your\folderhere,.\myfile.exe,.\path\to\my\'other file.txt' -ArchiveFilename my7zipfile.7z -OutputPath .\
```

**Comment by jmenashe** [comment]
This would be wonderful to have.

**Comment by thoemmi** [comment]
I've published the [pre-release version 2.1.1-beta0011](https://www.powershellgallery.com/packages/7Zip4Powershell/2.1.1-beta0011) including your PR. I give you some time to test it before I publish a final release.

**Comment by kborowinski** [comment]
@thoemmi @mattiasmaahl Unfortunately this commit ignores the `PreserveDirectoryRoot` switch and breaks cmdlets that require directory root to be preserved in 7z archive (which is most of out production modules that use 7Zip4PowerShell).

Example:
1. Create `Test` folder with one file in it.
2. Compress with `Compress-7Zip -ArchiveFileName 'C:\Test.7z' -Path 'C:\TEST\' -PreserveDirectoryRoot -Verbose`
3. The `Test.7z` archive should have `Test` folder with one file in it unfortunately it's not the case anymore.

Details:

7Zip4PowerShell 2.1.0

```powershell
[11][2022-06-25 13:07:21][00:00:00.002] C:\
[7.3][Bukem@ATLANTIS] > gmo 7Zip4PowerShell

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   2.1.0                 7Zip4PowerShell                     {Compress-7Zip, Expand-7Zip, Get-7Zip, Get-7ZipInformation}

[12][2022-06-25 13:07:23][00:00:00.006] C:\
[7.3][Bukem@ATLANTIS] > gci C:\TEST\

        Directory: C:\TEST


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a---         2021-12-22 17:08:40           3990 License.txt

[13][2022-06-25 13:07:37][00:00:00.020] C:\
[7.3][Bukem@ATLANTIS] > Compress-7Zip -ArchiveFileName 'C:\Test.7z' -Path 'C:\TEST\' -PreserveDirectoryRoot -Verbose
VERBOSE: 1 files found for compression
VERBOSE: Compressing License.txt
VERBOSE: Compression finished
[14][2022-06-25 13:08:10][00:00:00.014] C:\
[7.3][Bukem@ATLANTIS] > Get-7Zip C:\Test.7z

Index          : 0
FileName       : TEST\License.txt
LastWriteTime  : 2021-12-22 17:08:40
CreationTime   : 2022-06-25 13:09:17
LastAccessTime : 2022-06-25 13:09:17
Size           : 3990
Crc            : 3645865721
Attributes     : 32
IsDirectory    : False
Encrypted      : False
Comment        :
Method         : LZMA2:12


[15][2022-06-25 13:09:17][00:00:00.050] C:\
[7.3][Bukem@ATLANTIS] >
```
vs

7Zip4PowerShell 2.1.1-beta0011

```powershell
[3][2022-06-25 13:10:29][00:00:00.003] C:\
[7.3][Bukem@ATLANTIS] > gmo 7Zip4PowerShell

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   2.1.1      beta0011   7Zip4Powershell                     {Compress-7Zip, Expand-7Zip, Get-7Zip, Get-7ZipInformation}

[4][2022-06-25 13:10:31][00:00:00.057] C:\
[7.3][Bukem@ATLANTIS] > gci C:\TEST\

        Directory: C:\TEST


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a---         2021-12-22 17:08:40           3990 License.txt

[5][2022-06-25 13:10:40][00:00:00.036] C:\
[7.3][Bukem@ATLANTIS] > Compress-7Zip -ArchiveFileName 'C:\Test.7z' -Path 'C:\TEST\' -PreserveDirectoryRoot -Verbose
VERBOSE: 1 files found for compression
VERBOSE: Compressing License.txt
VERBOSE: Compression finished
[6][2022-06-25 13:10:46][00:00:00.096] C:\
[7.3][Bukem@ATLANTIS] > Get-7Zip C:\Test.7z

Index          : 0
FileName       : License.txt
LastWriteTime  : 2021-12-22 17:08:40
CreationTime   : 2022-06-25 13:10:53
LastAccessTime : 2022-06-25 13:10:53
Size           : 3990
Crc            : 3645865721
Attributes     : 32
IsDirectory    : False
Encrypted      : False
Comment        :
Method         : LZMA2:12


[7][2022-06-25 13:10:53][00:00:00.049] C:\
[7.3][Bukem@ATLANTIS] >
```

**Comment by thoemmi** [comment]
@kborowinski Thanks for your detailed analysis. I've reverted this PR and published [a version](https://www.powershellgallery.com/packages/7Zip4Powershell/2.1.1-beta0012) without it.

**Comment by kborowinski** [comment]
So far, so good. If no one reports errors then, I think, you're good to release the new version.

**Comment by thoemmi** [comment]
@kborowinski [v2.2](https://www.powershellgallery.com/packages/7Zip4Powershell/2.2.0) is published

**Pull request merged**
